/**
 * Generates src/algorithms/manifest.ts — the lightweight metadata index.
 *
 * The app needs metadata for all 254 problems immediately (sidebar, search, patterns, topics)
 * but the heavy parts of an algorithm — three languages of source, the step generator, the
 * per-line explanations — only for the ONE problem selected. Importing everything eagerly put
 * ~3.2 MB in the initial bundle.
 *
 * This script reads the real algorithm objects and emits just the metadata, plus the module
 * path so the registry can lazily import an implementation on demand. `manifest.test.ts`
 * asserts the committed output still matches the source, so it cannot silently drift.
 *
 * Run with: npm run manifest
 */
import { writeFileSync } from 'node:fs';
import { categories } from '../src/algorithms/index.ts';
import { getApproaches } from '../src/utils/approaches.ts';
import { getTopicsFor } from '../src/utils/topics.ts';
import { getPatternName } from '../src/utils/patterns.ts';

const CATEGORY_DIRS: Record<string, string> = {
  'arrays-hashing': 'arrays-hashing',
  'two-pointers': 'two-pointers',
  stack: 'stack',
  'sliding-window': 'sliding-window',
  'binary-search': 'binary-search',
  'linked-list': 'linked-list',
  backtracking: 'backtracking',
  tries: 'tries',
  heap: 'heap',
  trees: 'trees',
  'dp-1d': 'dp-1d',
  'dp-2d': 'dp-2d',
  greedy: 'greedy',
  intervals: 'intervals',
  'math-geometry': 'math-geometry',
  'bit-manipulation': 'bit-manipulation',
  graphs: 'graphs',
  'advanced-graphs': 'advanced-graphs',
};

// id -> the module file that exports it, discovered by matching exports against ids.
const { readdirSync } = await import('node:fs');
const moduleFor = new Map<string, string>();
for (const dir of Object.values(CATEGORY_DIRS)) {
  for (const file of readdirSync(`src/algorithms/${dir}`)) {
    if (!file.endsWith('.ts') || file.endsWith('.test.ts')) continue;
    const mod = await import(`../src/algorithms/${dir}/${file}`);
    for (const value of Object.values(mod)) {
      const v = value as { id?: string };
      if (v && typeof v === 'object' && typeof v.id === 'string') {
        moduleFor.set(v.id, `./${dir}/${file.replace(/\.ts$/, '')}`);
      }
    }
  }
}

const q = (s: string) => JSON.stringify(s);

const body = categories
  .map((c) => {
    const entries = c.algorithms
      .map((a) => {
        const approaches = getApproaches(a).map(
          (ap) =>
            `      { id: ${q(ap.id)}, name: ${q(ap.name)}, timeComplexity: ${q(
              ap.timeComplexity
            )}, spaceComplexity: ${q(ap.spaceComplexity)} },`
        );
        const modulePath = moduleFor.get(a.id);
        if (!modulePath) throw new Error(`no module found for ${a.id}`);
        return [
          `    {`,
          `      id: ${q(a.id)},`,
          `      name: ${q(a.name)},`,
          `      category: ${q(a.category)},`,
          `      difficulty: ${q(a.difficulty)},`,
          `      patternName: ${q(getPatternName(a))},`,
          `      problemUrl: ${a.problemUrl ? q(a.problemUrl) : 'undefined'},`,
          `      timeComplexity: ${q(a.timeComplexity)},`,
          `      spaceComplexity: ${q(a.spaceComplexity)},`,
          `      topics: [${getTopicsFor(a).map(q).join(', ')}],`,
          `      module: ${q(modulePath)},`,
          `      approaches: [`,
          ...approaches,
          `      ],`,
          `    },`,
        ].join('\n');
      })
      .join('\n');
    return [
      `  {`,
      `    id: ${q(c.id)},`,
      `    name: ${q(c.name)},`,
      `    icon: ${q(c.icon)},`,
      `    algorithms: [`,
      entries,
      `    ],`,
      `  },`,
    ].join('\n');
  })
  .join('\n');

const out = `// GENERATED by scripts/generateManifest.mts — do not edit by hand.
// Run \`npm run manifest\` after adding or changing a problem.
// manifest.test.ts asserts this file still matches the real algorithm objects.
import type { CategoryMeta } from './manifestTypes';

export const metaCategories: CategoryMeta[] = [
${body}
];
`;

writeFileSync('src/algorithms/manifest.ts', out);
const total = categories.reduce((n, c) => n + c.algorithms.length, 0);
console.log(`manifest written: ${total} problems, ${(out.length / 1024).toFixed(0)} KB`);
